# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b94ae1c15ff4a9039a414b894a8855df80011e0723bfda30add0df08c1df17e6a66ac4954f63a45170d43228a66e37ea1b68bcc818b95c4d84eb9185bcd7100f

test:
  secret_key_base: 08876f575c876dff80a0d18e920a54672b4f94f511f9ad0c6368a05335c7f135f687d92d676dc4d4e3f8673343dd4f8a43cb1e5209392b0d7462f5a5b7ab7e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
